### ISSUE TITLE
Reorganize the microservice architecture and upgrade to serverless 1.x in the process

### ISSUE THREAD

**Issue by ccverak** [MoonMail/MoonMail#335]
Things to re-organize:

- api
- events
- private
- extensions
- lists

To be relocated into:

- lists-microservice
- emails-microservice
- campaigns-microservice
- automations-microservice
- webbooks-microservice
- users-microservice
- templates-microservice
- support

Since **private** was a completely different repo, there is a lot of mixed and duplicated code in there. A deep process of de-duplication should be done as well after the integration.

**Comment by alexandresaiz** [comment]
Closing as it's already in progress
