### ISSUE TITLE
listRecipientsHttp function don't work

### ISSUE THREAD

**Issue by DiegoPires** [MoonMail/MoonMail#340]
I jus't deployed a new moonmail app in AWS, things seens to work fine, except the function "listRecipientsHttp"

When I call it I see the following error in my logs:

```
{
    "message": "Function not found: arn:aws:lambda:us-east-1:187680139068:function:spektrum-moonmail-lists-dev-**searchRecipientsRaw**",
    "code": "ResourceNotFoundException",
    "time": "2018-06-26T18:26:18.012Z",
    "requestId": "6ac99824-796e-11e8-b2e7-11996088f9da",
    "statusCode": 404,
    "retryable": false,
    "retryDelay": 21.785371645320815
}
```
What is this function "searchRecipientsRaw", I can't see to find it to deploy. I can just deploy "listRecipientsHttp"

**Comment by alexandresaiz** [comment]
Closing this issue as if there's deeper help needed, we suggest to post the questions to [StackOverflow](https://stackoverflow.com/questions/tagged/moonmail)
