### ISSUE TITLE
Unsubscribe link not working

### ISSUE THREAD

**Issue by DiegoPires** [MoonMail/MoonMail#372]
The unsubscribe link it's not working, I realized it required the variable "unsubscribedCallbackUrl" to be set to something, but don't know what is it and there's nowhere in the docs talking about it

**Comment by JefersonS** [comment]
I'm sorry on the delay, we are in the middle of the process of rebuilding things here.

This variable is related to the redirect after a Recipient is subscribed, you can specify it in your _meta variables.

I'm no sure right now, but if you leave a default Url the code won't ping it, so you'll be able to deploy it.
