### ISSUE TITLE
segments based on click-through of specific campaigns or even links

### ISSUE THREAD

**Issue by aspiers** [MoonMail/MoonMail#378]
Currently segments can be created based on actions relating to a certain number of campaigns, or campaigns within a particular time window:

![a__cetza](https://user-images.githubusercontent.com/100738/49656198-9af83000-fa34-11e8-942b-bf17d1703ef8.png)

![-a3mfyk9](https://user-images.githubusercontent.com/100738/49656190-95024f00-fa34-11e8-9787-527ef9a2cb0a.png)

However it would be very useful to be able to create segments based on more fine-grained actions, e.g.

- A user registers interest on a particular topic by clicking any link within a specific campaign
- A user registers interest on a particular topic by clicking a specific link within a specific campaign
- A user registers interest on a particular topic through some external action (e.g. a comment on a facebook page), and I want to track that interest by manually adding them to the segment.

Currently if I have an overall product or topic area but also need to track interest in specific sub-topics (e.g. different features or aspects of the product), it seems I would need to create a list for each sub-topic, and then have people's subscriptions duplicated across multiple lists if they have multiple interests.  And this doesn't seem like a good solution, hence my request for more fine-grained segmentation control above.  Or am I missing something?

I would be more than happy to help test the development of this feature!  In an ideal world I could even help with the coding, although I fear I'm very unlikely to have enough free time for that (unless it's really easy and I got some pointers from people who know the code well).

**Comment by JefersonS** [comment]
We greatly appreciate your suggestion, and even more your availability to help us on testing.

Right now we are moving tides a little bit, MoonMail is in the middle of a refactoring and issues like the one you stated here are being reevaluated and fixed as the process goes.

Unfortunately we are not able to tell details on release dates or specifically what is being changed, but you can be sure we have these sort of issues in mind.

As soon as the major parts are released we will have a full document stating all the changes and what's new. 

_PS._ _As you've come here looking for these changes, please, send an email to our support asking to be notified as soon as what you asked comes out (feel free to mention my name, and they will know where to redirect you :D)._
