### ISSUE TITLE
Project cannot be deployed to AWS due to node.js 4.3 deprecation

### ISSUE THREAD

**Issue by kalevalp** [MoonMail/MoonMail#386]
The services that use Serverless 0.5.4 all use the nodejs4.3 runtime. AWS stopped supporting nodejs4.3, and I haven't found any way to change the runtime of the functions.

**Comment by alexandresaiz** [comment]
@kalevalp answered via email

**Comment by kryjex** [comment]
I also have this doubt. You found/know how can I deploy?

**Comment by chrs3** [comment]
Hi, I'm also having this issue. Have tried looking everywhere for a solution. Has anyone got a way around this please?
