### ISSUE TITLE
Remove automations

### ISSUE THREAD

**Issue by alexandresaiz** [MoonMail/MoonMail#391]
The whole automations service has been deprecated and it is to be fully removed along with all dependencies. MoonMail stays as an only mass marketing email service.

**Comment by hridayeshgupta** [comment]
What will be the alternatives to automations, scheduling followup emails in future?

**Comment by aspiers** [comment]
I have the same question. Without those I fear it will be useless for me in the future 🤔

**Comment by JefersonS** [comment]
We were considering the ideia of removing automations due to some internal problems. However after some discussion we decided it was not the best approach to the issue and decided to keep it.
