### ISSUE TITLE
sls function deploy failed, can't find module handler

### ISSUE THREAD

**Issue by JackieWhite** [MoonMail/MoonMail#396]
Hello,
Thank you first for the great project.
I am having trouble with `sls function deploy` command. I got the following error:

Serverless: | events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './handler' from '/home/jackie/Desktop/MoonMail/_meta/_tmp/updateUserReputation@1557570598954/events/users/updateUserReputation'
    at /home/jackie/Desktop/MoonMail/node_modules/resolve/lib/async.js:61:35
    at load (/home/jackie/Desktop/MoonMail/node_modules/resolve/lib/async.js:80:43)
    at onex (/home/jackie/Desktop/MoonMail/node_modules/resolve/lib/async.js:105:17)
    at /home/jackie/Desktop/MoonMail/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:152:21)

I have tried `yarn add global handler but it doesn't work.

nodejs v8.16.0
yarn 1.15.2

And it keeps saying that uglify-js failed and SyntaxError? Is that a problem?

Thank you!

**Comment by JefersonS** [comment]
Hello,

What version of SLS are you using and what service are you trying to deploy?

**Comment by JackieWhite** [comment]
I run command
`yarn global add serverless@0.5.6` in the root directory

and `yarn install` in every subdirectory (events, api, extensions, events-router, etc)there. (that is I'd like to deploy every service, am I getting it right?)

then `sls resources deploy` in the root directory (succeeded)
then `sls function deploy` in the root directory (failed with "can't find module handler")

And now `sls -v` gives 0.5.6

Thank you!

**Comment by JefersonS** [comment]
That's weird, it should try to deploy all functions, and in case anything happened it should give a better error.

Can you try going to any function folder and do a `sls dash deploy -s STAGE -r REGION`?

That will help finding the issue.

**Comment by JackieWhite** [comment]
Thank you for your advice ! I'll try again as soon as possible.

**Comment by 143umohsinkhan** [comment]
@JackieWhite Hi, hope you good. did you get a chance to deploy those functions? I tried but did not get success. my env is the same which you mentioned above.
Thanks 
MK
