### ISSUE TITLE
Why serverless 0.5 and 1.0?

### ISSUE THREAD

**Issue by tcurdt** [MoonMail/MoonMail#397]
Is there a specific reason why the install requires serverless 0.5 (as a global install?) and is not getting upgraded to 1.x?

If there is the reason it would be good to have it in the README.

**Comment by JefersonS** [comment]
MoonMail was initially released when SLS 1.0 was not yet available.

Later on we started creating some new services using SLS 1.0 and keeping the old ones in SLS 0.5. Right now we are in the middle of an update to move everything to SLS 1.0.

**Comment by tcurdt** [comment]
@JefersonS is there a branch where this is happening?

**Comment by JefersonS** [comment]
We have a separate project, but the branch is not public yet.

As soon as we have it finished we will update the whole repository.

**Comment by medampudi** [comment]
@jefersonS this has been my number request on all the interfaces I have had with moonmail team. If possible let me contribute in some capacity so that I can Be part of its growth to the scale it gives all the users.

**Comment by prachetasp** [comment]
@JefersonS looking forward to the 1.0 release. Is there any (really rough is fine) timeline you could share with us? We are evaluating MoonMail for a fairly large deployment, but I don't want to orphan resources on 0.5 if the 1.0 update is imminent. Thanks!

**Comment by JefersonS** [comment]
@medampudi right now is a bit complicated to measure efforts and share workloads. We are taking things slowly as we have an app already in production and another in the oven. However we appreciate the help and will reach out when in need.

@prachetasp we are in the phase of fixing what we have in production, and then replicate it here as Open Source. I can say we are close to finishing fixing Production side, and as soon as we finish it we will be able to move full force to Open Source.
It's really hard to give a timeline tough, we are facing some unexpected barriers, and might find even more. We will make sure to keep you guys updated as soon as we have some good news.

Finally, sorry on the delay guys, sometimes I end up missing one or another notification.

**Comment by prachetasp** [comment]
Thanks for the detailed explanation! As others on this thread have said -
if there is anything the community can help with to move this forward let
us know.
