### ISSUE TITLE
API cannot be deployed

### ISSUE THREAD

**Issue by cecarini** [MoonMail/MoonMail#398]
All services that use Serverless 0.5.4, require the nodejs4.3 runtime. AWS stopped supporting nodejs4.3, and I haven't found any way to change the runtime of the functions.

There was another ticket about this, but it has been closed without a response, so I thought I would submit a new one.

Thanks!

**Comment by JefersonS** [comment]
Hello @cecarini, yes AWS has ceased the support for Node 4.3, and Serverless 0.5 is a long forgotten version.

We are at this moment working to move everything to SLS 1.0, we are not able to set a deadline right now, and I know that's problematic, however I assure you we are updating the Open Source side of MoonMail and will soon have a better app here.
